### ISSUE TITLE
SlickGrid Dissapearing Text in Frozen Column on Horizontal Scroll

### ISSUE THREAD

**Issue by stplajay** [mleibman/SlickGrid#1076]
I have used SlickGrid in my project. Grid contains 30 columns. Initially grid works fine. it has horizontal as well as vertical scroll. I have frozen first column.
Issue is that when i scroll it horizontally and reached at right most and then after vertical scrolling frozen column data doesn't display.
Any suggestion please help.

![before](https://cloud.githubusercontent.com/assets/13213492/8799412/7c965dd4-2fc7-11e5-9262-f18e20c6a73f.png)

![after](https://cloud.githubusercontent.com/assets/13213492/8799419/82aeffc8-2fc7-11e5-8144-e7d8b93d6e0b.png)

**Comment by Francks11** [comment]
Hello @stplajay ,

the original plugin here doesn't support frozen columns and frozen rows.

I think you use this plugin from this fork https://github.com/ddomingues/X-SlickGrid

I have fixed this bug.

You can retrieve the worked code from https://github.com/ddomingues/X-SlickGrid or from my fork here : https://github.com/Francks11/X-SlickGrid

:-)

**Comment by stplajay** [comment]
Hi, thanks for your quick response. I have incorporated the changes and seems working as expected.
Thanks once again :)
