### ISSUE TITLE
Frozen Columns not rendered

### ISSUE THREAD

**Issue by shabarinadh** [mleibman/SlickGrid#1085]
I have around 120 columns and 2000 rows with 3 frozen columns, Everything is working fine as expected, until I find a issue with rendering frozen columns. 
Steps to Reproduce :
1) Fast drag vertical scroll bar to bottom of the grid
2) Fast drag horizontal scroll bar to somewhere middle..
3) Now try to drag vertical scroll bar fast/slow upwards, 

One can see that, frozen columns are not rendered , only blank cells are shown...

Appreciate , If some one could find the solution...

**Comment by 6pac** [comment]
Have you tried my [Alternate Master] (https://github.com/6pac/SlickGrid/wiki) ? It has a lot of bug fixes and patches, particularly if you are using the latest jQuery versions, which don't work so great with the MLeibman master :-(

**Comment by shabarinadh** [comment]
Thanks for your suggestion, will try this and get back to you , if reproduced

**Comment by shabarinadh** [comment]
Hey,

There is no freeze columns feature in 'alternate master'

**Comment by Francks11** [comment]
Hi this bug is fix on my repo. Try :-)

**Comment by shabarinadh** [comment]
Could you please send did p link for zip download..

**Comment by shabarinadh** [comment]
Deep link*

**Comment by Francks11** [comment]
https://github.com/Francks11/X-SlickGrid

**Comment by shabarinadh** [comment]
Thank you, will check

**Comment by 6pac** [comment]
I don't think freeze columns is in MLeibman either, is it ?

**Comment by shabarinadh** [comment]
It is...

**Comment by 6pac** [comment]
I don't see how it could be, the 'Alternate Master'  is based on a direct pull from the very latest in the MLiebman repo.
