### ISSUE TITLE
Issue while scrolling down in the grid with grouping

### ISSUE THREAD

**Issue by manokondrangi** [mleibman/SlickGrid#1129]
While expanding one group when all groups are in collapsed state, I am getting lesser rows in the group than it actually contains. This seems happening bcz of virtual scrolling.

http://mleibman.github.io/SlickGrid/examples/example-grouping

Steps to reproduce:
1. choose 500k rows
2. Collapse all groups
3. Expand one group in bottom of grid view (current viewport)
4. Expand one group from top
5. Scroll down

![image](https://cloud.githubusercontent.com/assets/13063879/19651661/6aafd530-9a2b-11e6-9ff8-0c36229efe16.png)

You can see lesser rows in the group than it contains. And its working good if we scroll little more and scroll up back to the previous position.

**Comment by 6pac** [comment]
There have been a number of grouping bugs identified and fixed in my repo, give it a try: https://github.com/6pac/SlickGrid 
You should be using that repo anyway, the MLeibman branch is getting very out of date now..

**Comment by manokondrangi** [comment]
Thank you @6pac ..
