### ISSUE TITLE
Transfer Ownership of Repo to 6pac

### ISSUE THREAD

**Issue by tobya** [mleibman/SlickGrid#1146]
Hi @mleibman 

Any chance you might transfer ownership of the root/master project to @6pac as his repo seems to be the most alive and he could keep this amazing project alive.  At the moment it seems to be a bit confusing.

Thanks

Tobya

**Comment by 6pac** [comment]
thanks @tobya, i did raise the issue with @mleibman some time ago. he commented that my repo essentially taking over maintenance was the way open source software should work. at that time he did put a note on his main page. perhaps we need to ask for something more definitive.
