### ISSUE TITLE
Group by with checkbox in Slick grid

### ISSUE THREAD

**Issue by chaitanya121** [mleibman/SlickGrid#1152]
Hi All,

I want to implement group by with check box in slick grid.

If group by is applied and check box is selected on group by header row then all child on that group should be selected..

wanted to apply group level checkbox selection..

Is there any in build Plugin available to achieve above functionality.  

Thanks
Chaitanya

**Comment by harit2101** [comment]
Hey,
This would be helpful.

http://6pac.github.io/SlickGrid/examples/example-grouping-checkbox-row-select.html

**Comment by 6pac** [comment]
this repo is essentially dead. the 6pac repo carries on its work. just use that.
