### ISSUE TITLE
Rowselection after render event

### ISSUE THREAD

**Issue by GitHubOrim** [mleibman/SlickGrid#1158]
Hi,
what is the right event to store grid.setSelectedRows([0])
I want to check after page loaded or grid loaded... if rowcount > 0 then select first row
I can`t get it to work...
Or do i need to insert timeout...

**Comment by 6pac** [comment]
Questions like this should be posted on StackOverflow. GitHub is for bugs.
This said, if you start with one of the examples that uses RowSelectionModel, I don't think there should be a problem with your code if in comes after all the initialisation.
