### ISSUE TITLE
Cloumn formatting - Prefix dots while text is trimmed

### ISSUE THREAD

**Issue by dileepkumars1** [mleibman/SlickGrid#1162]
Hi,

Is there any way to prefix the dots instead of suffixing the same while the value is not fit into the column? I have a numeric column for which the last digits should not be trimmed when not fit in cell.

Any possibilities? Please help

**Comment by 6pac** [comment]
I think the dots may be put there by the web browser when the value is too long to fit in the cell. If so, it's automatic. You could write a formatter to truncate and add leading dots, it wouldn't be too hard. See the formatter example and Google about leading truncation with ellipsis

**Comment by dileepkumars1** [comment]
Thank you for the prompt response. It is apt for my requirement.
