### ISSUE TITLE
div movement in slick grid 

### ISSUE THREAD

**Issue by pcuser121** [mleibman/SlickGrid#1171]
I have created slickgrid which contains two divs separated by column separator.
Left side div contains many columns with scroll bar available on horizontal side. Right side div contains many columns with scroll bar available on horizontal side.I wanted to know how can we achieve div movement from one div to another div from left to right and vice versa.

when we take separator from left to right, left side div should expand and right side should get compressed so as adjust 100% width.

when we take separator from right to left, right side div should expand and left side should get compressed so as adjust 100% width.

here div is nothing but panel. 

[SlickGridColumnIssue.xlsx](https://github.com/mleibman/SlickGrid/files/1368131/SlickGridColumnIssue.xlsx)

**Comment by 6pac** [comment]
Some people have done a synchronised-split-grid thing, not sure if the resizing is part of it. Perhaps we can get an example from one or more of those people?

https://github.com/6pac/SlickGrid/issues/171
@gkraser ?

https://github.com/6pac/SlickGrid/pull/45
@lucax88x ?

**Comment by gkraser** [comment]
My implementation of fixed columns is not universal. It is highly integrated with the ExtJS. I do not need horizontal scrolling in a fixed part. Therefore, when changing the width or number of columns in a fixed part, I calculate the width of the fixed columns and set the with for the divs that contains the grid with fixed columns. And I do resizeCanvas().

**Comment by pcuser121** [comment]
This is handled using jquery itself by setting max-width in percentage.
so when you are scrolling from left to right, at any point cursor stops, so we will take that position in terms of percentage let's say 40
so we will give 40% to left hand hand side grid & (100-40) i.e. 60% to right hand side grid.
so in this way we can have dynamic grid width based cursor movement.

I am extremely sorry for my late comment.
I am closing this issue now.

**Comment by 6pac** [comment]
No worries. Remember this repo is dead - use: github.com/6pac/SlickGrid
