### ISSUE TITLE
Lock the columns 

### ISSUE THREAD

**Issue by Marcod93** [mleibman/SlickGrid#1174]
Hello,
I would like to know if there is an attribute for the columns of a form to make sure that by scrolling the table you lock a certain column and remain visible.

Thanks!

**Comment by 6pac** [comment]
That's called 'frozen columns'. It's not implemented in the main project, but I'd suggest googling around a bit, there are a few repos that have implemented this feature, JLynch in particular.

I'd like to implement it in [my repo](https://github.com/6pac/SlickGrid/wiki), but it would take a significant amount of time to integrate. May get around to it some day, but not for a few years, I reckon.

**Comment by 6pac** [comment]
https://github.com/6pac/SlickGrid/issues/26
