### ISSUE TITLE
Slickgrid header row filtering empty cells not working in example

### ISSUE THREAD

**Issue by ghost** [mleibman/SlickGrid#1179]
I was looking into this example and saw that filtering does not happen when searching for empty cells. This means I typed any string in the filterbox and then removing the string. However, when debugging it locally and making some cells empty, I saw that dataview.refresh() is called upon an empty input, the grid just doesn't display the empty cells.

In my application I have a use case where one might want to search for all cells that have no content, so my question is, is this something that can be changed, or is it baked deeply under the Slickgrid hood?

I can understand the use case in the linked example, as it already loads the filters on page load, but in my application the filter is only applied after a confirmation button click.

Thanks for your help.

**Comment by 6pac** [comment]
Answered on StackOverflow. Note that this repo is no longer active, you should use: https://github.com/6pac/SlickGrid/wiki

**Comment by ghost** [comment]
Thanks for the response, I'll close this.
