### ISSUE TITLE
custom filter for selecting all rows in grid

### ISSUE THREAD

**Issue by avi2911** [mleibman/SlickGrid#1184]
I'm having scenario in which all the rows need to be selected if it contains a check box else the row should not be selected.Help me solve out.

Thanks in advance..

**Comment by 6pac** [comment]
See [slickgrid.net](http://slickgrid.net/SubmitAnIssue.html). Ask on StackOverflow. Give a more detailed question with an image if possible.

**Comment by avi2911** [comment]
Sorry for the late reply..

Please,see the snapshot in that im not having checkbox in the row but,it is still selected.How to set filter for that.?

![image](https://user-images.githubusercontent.com/38031548/41526564-3dd37fba-7302-11e8-9da4-076bd27a178b.png)

1st row should not be selected because there is no checkbox.

**Comment by 6pac** [comment]
... follow previous advice (1 out of 3 so far) ....

**Comment by avi2911** [comment]
Hi,

I've asked this in stackoverflow no response yet.Is it possible to get a solution.

Please find it in the link,

https://stackoverflow.com/q/51378625/9960181

**Comment by avi2911** [comment]
Got the solution.Find it in the above link
