### ISSUE TITLE
the onRowCountChanged event does not fire when the data row is 0

### ISSUE THREAD

**Issue by bthachdev** [mleibman/SlickGrid#1189]
If we delete an only item in the grid, the onRowCountChange does not fire.

Maybe problem is in these code in slick.dataview.js ? 
What if rows.length is 0 and countBefore is 0 after we delete an item.

if (countBefore != rows.length) {
    onRowCountChanged.notify({previous: countBefore, current: rows.length}, null, self);
}

**Comment by 6pac** [comment]
Note that the event is only called in ```refresh()``` - are you calling it?

Also note this repo is now unmaintained - see slickgrid.net for more details.

**Comment by bthachdev** [comment]
yes, I called it.

**Comment by 6pac** [comment]
what example are you using to reproduce the behaviour?

**Comment by bthachdev** [comment]
The issue happen in our code, not in slickgrid library.
So I close this.
