### ISSUE TITLE
Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [mleibman/SlickGrid#1198]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by 6pac** [comment]
Not really. There are unit tests but these are based on a javascript test framework based in HTML pages.
Note that this repo is no longer active, go [here](https://github.com/6pac/SlickGrid).

For reasons why CI is not supported, go [here](https://github.com/6pac/SlickGrid/wiki/The-SlickGrid-Manifesto)

**Comment by gustavosizilio** [comment]
I see. Thanks very much!
