### ISSUE TITLE
슭릵긋맇듯 씄긲 덥럽겝 엏렵넿

### ISSUE THREAD

**Issue by ghost** [mleibman/SlickGrid#1207]
에라이

**Comment by ninezero90hy** [comment]
@underTheTitle Should I curse so that I don't understand Korean? That's very rude.

**Comment by ninezero90hy** [comment]
Translation :

> Slickgrid a dirty little hard to use it.

**Comment by 6pac** [comment]
You might try using the 6pac fork, that's the current modern version.  Ghiscoding also has angular and aurelia versions. 

https://github.com/6pac/SlickGrid/wiki/The-SlickGrid-Manifesto

**Comment by ghost** [comment]
Sorry if you're mad at me.
I'm actually using slickgrid well.
Thanks for making a good library.
