### ISSUE TITLE
Better way to define parent item?

### ISSUE THREAD

**Issue by tizmagik** [mleibman/SlickGrid#215]
Is there a better way to define the `parent` index for SlickGrid data when defining a collapsable grid (treeview)?

It seems cumbersome to have to define the `parent` index as the actual array index value in SlickGrid.

To illustrate what I'm referring to specifically, I'll reference SlickGrid's Collapsable example, http://mleibman.github.com/SlickGrid/examples/example5-collapsing.html

The issue is when defining 'child' tree elements, the parent index must be the actual array index value of the grid data. This is cumbersome when appending multiple data sources and combining into one grid. Ideally, it would be nice if the parent property is defined as just a reference to the actual parent object, OR, if data items can be defined with a children: [] property that takes nested row values/data items for example.

Does this make sense? If not, please let me know and I will try and explain this a little better.

Many thanks in advance for any and all insights!

**Comment by mounicanaidu** [comment]
Its a bit late to add here, but I recently used SlickGrid to create a combined tree view and column grouping and the parent child relationship was tedious to achieve with the data I had. Hence I created a small plugin using SlickGrid to automatically create parent child relationships. This includes, aggregations and parent assignment. Hope this helps someone who wants to achieve this easily.

Link: https://github.com/mounicanaidu/SlickGrid-TreeView-Column-Grouping
