### ISSUE TITLE
Virtualization fails above 50k recods in IE

### ISSUE THREAD

**Issue by milang** [mleibman/SlickGrid#22]
To reproduce, update "example1-simple.html" data population loop to go to 100,000 (instead of 500). Now load the HTML file in IE (I tested in v8 and simulated v7). When you use the scrollbar to move to the very end, instead of "Task 99999" you see "Task 47721" in IE8 and "Task 53686" in simulated IE7.

I think this effect is caused by IE handling height of the grid-canvas element incorrectly. If you look at the above grid in Developer Tools, it says "height: 1342177.27px" which is clearly incorrect. This seems to be a limitation of IE and the only way to "fix" it (I think) is to also virtualize the grid-canvas height...

**Comment by quicksnap** [comment]
Wanted to say thank you for this! Even six years later, this proved useful. I ported this chunk of logic over to React and it's working very nicely. https://github.com/Extensis/slick-scroll

**Comment by jounik** [comment]
Just looked at the fiddle also, and works brilliantly, even after six years :smile: 

@quicksnap you can overcome the Safari momentum scrolling issue by adding `pointer-events: none;` to 
the content/rows during scrolling.

**Comment by quicksnap** [comment]
@jounik Holy crap, I'm going to try that out! Thanks!

**Comment by quicksnap** [comment]
It works! Thank you so much @jounik!

**Comment by quicksnap** [comment]
http://jsfiddle.net/SDa2B/263/

**Comment by arizale** [comment]
hi, can i build sclickgrid programmatically?

**Comment by 6pac** [comment]
There is an npm package: ```npm install slickgrid```

But see [the manifesto](https://github.com/6pac/SlickGrid/wiki/4-The-SlickGrid-Manifesto)

**Comment by arizale** [comment]
i want to create slickgrid with my data but the scroll is horizontal

**Comment by arizale** [comment]
or this http://jsfiddle.net/SDa2B/263/ any example of horizontal scroll?

**Comment by 6pac** [comment]
don't think that's possible. SlickGrid uses the browser built in scroll bar.

If you still want to use SlickGrid [my repo](https://github.com/6pac/SlickGrid) is current, check out the readme. this repo is no longer active. download the zip package. you should be able to run the examples (in the ```examples``` folder) locally. if you still have problems, please open an issue there.

**Comment by arizale** [comment]
i will open new issue for example scroll. what i can do that?

**Comment by arizale** [comment]
scroll horizontal i mean

**Comment by 6pac** [comment]
open an issue in my repo. 
but i don't know what you mean by horizontal scroll, you'll need to explain that. If you mean using a horizontal scroll bar to scroll through data, you definitely can't do that with any version of SlickGrid.

**Comment by thadguidry** [comment]
@6pac Horizontal scrolling is also fast and done very well in SlickGrid http://mleibman.github.io/SlickGrid/examples/example-spreadsheet.html

**Comment by 6pac** [comment]
@thadguidry sure, that's scrolling through column data horizontally, using the browser's built in scrolling. what i meant is, you can't scroll vertically through the row data, using a horizontal scroll bar. that's how i interpreted this request. i might be wrong :-)
