### ISSUE TITLE
Slickgrid Grouping

### ISSUE THREAD

**Issue by ramsunder** [mleibman/SlickGrid#310]
I can't able to retain the selected rows when expanding or collapsing in a slickgrid in which grouping has done. Please let me know the solution for this issue.

**Comment by prajeshece91** [comment]
I am having the same issue. Any solution there. Pls send solution link.

**Comment by 6pac** [comment]
any help?: http://stackoverflow.com/questions/15521057/slickgrid-selection-issues-on-sort
