### ISSUE TITLE
grid not sorting after grid.setSortColumns()

### ISSUE THREAD

**Issue by ghost** [mleibman/SlickGrid#325]
Hi,

Data is displayed, sorting indicators added but the data is not sorted.

```
grid.setColumns(colums);
dataView.beginUpdate();
dataView.setItems(data);
dataView.endUpdate();

grid.setSortColumns([{"columnId":"2","sortAsc":true}]);

grid.invalidate();
grid.render();
```

**Comment by Gaurav-Rai** [comment]
I have too many blank spaces in my column, when I'm sorting using grid.onSort.subscribe(), the data is getting sorted alphabetically but there are random gaps because of empty spaces, I am not able to find out a way to remove the white space in the sorted column.
