### ISSUE TITLE
Calling grid.invalidate() stops rows from being activated

### ISSUE THREAD

**Issue by omnimike** [mleibman/SlickGrid#437]
Here's a JSFiddle demonstrating the problem:
http://jsfiddle.net/Omnimike/x2FWs/
To reproduce it:
1. Click on a row to make it active.
2. Scroll the grid so that row is no longer visible.
3. Click "Invalidate" to call grid.invalidate().
4. Clicking on another row no longer makes it active, instead throwing "Uncaught TypeError: Cannot read property 'rowNode' of undefined ".

This only happens is master, and seems to be related to a recent change to add an "active" class to the active row (that's where the exception is thrown from anyway). What seems to be the case is that when grid.invalidate() is called the active row is being removed from the dom if it isn't currently within the viewport (previously it seems like the active row was left in there even if it couldn't be seen).

Of course, I'm no slick grid expert. This is just my guess from doing a bit of digging.

**Comment by jitenthripola** [comment]
Thanks to provide this code . Its good solution.

**Comment by 6pac** [comment]
This repo is dead, please use this one: https://github.com/6pac/SlickGrid
