### ISSUE TITLE
checkboxSelectColumn plugin not allowing for edits (tab edit)

### ISSUE THREAD

**Issue by sunzyflower** [mleibman/SlickGrid#537]
I looked at the example here:

http://mleibman.github.com/SlickGrid/examples/example-checkbox-row-select.html

And I realized that when you are editing a cell you cannot tab to edit the next cell. You have to double click to edit, which makes adding new rows tedious.

On my implementation, I cannot edit cells on the new row until I click out to another row and then back to the cell I need to edit. Has anyone else run into this and how can I solve it?

**Comment by AlexandrChazov** [comment]
Thank you a very much, I had the same issue, you helped me a lot !!!

**Comment by 6pac** [comment]
Two things: using the grid option ```autoEdit``` will allow you to edit cells on focus, rather than clicking on them first.

Secondly this repo is long dead - you should be using: https://github.com/6pac/SlickGrid/wiki
