### ISSUE TITLE
Slow and choppy scroll on iPad

### ISSUE THREAD

**Issue by ThomasArdal** [mleibman/SlickGrid#573]
When visiting http://mleibman.github.com/SlickGrid/examples/example-optimizing-dataview.html from an iPad, scroll the list is slow and choppy. Would be cool to get a nice sliding feal on mobile devices the same way as on desktop.

**Comment by snprabu** [comment]
if i am using slick slider in one of my page, then the page loose smooth scroll in ios device. is anyone faced some problem like this?
