### ISSUE TITLE
Copy/paste doesn't work

### ISSUE THREAD

**Issue by provegard** [mleibman/SlickGrid#575]
Trying out SlickGrid, went for the copy/paste example:

http://mleibman.github.com/SlickGrid/examples/example-spreadsheet.html

Pasting from Excel using Ctrl-V doesn't work. Tested in Firefox, Chrome and IE9.

Copying from SlickGrid into Excel also doesn't work.

**Comment by alexcroox** [comment]
I achieved copy to system clipboard in the following simple way:

```
var ctrlDown = false,
ctrlKey = 17,
cmdKey = 91,
cKey = 67;

// Listen for CTRL or CMD key presses
$(document).keydown(function(e) {
    if (e.keyCode == ctrlKey || e.keyCode == cmdKey)
        ctrlDown = true;
}).keyup(function(e) {
    if (e.keyCode == ctrlKey || e.keyCode == cmdKey)
        ctrlDown = false;
});

// Combine the CTRL/CMD key press with C and we are ready to copy
$('.slick-viewport').keydown(function(e) {
    if (ctrlDown && (e.keyCode == cKey) && $('.slick-cell.active').length) {
        copyTextToClipboard($('.slick-cell.active').html());
    }
});

function copyTextToClipboard(text) {
    var textArea = document.createElement("textarea");

    // Place in top-left corner of screen regardless of scroll position.
    textArea.style.position = 'fixed';
    textArea.style.top = 0;
    textArea.style.left = 0;

    // Ensure it has a small width and height. Setting to 1px / 1em
    // doesn't work as this gives a negative w/h on some browsers.
    textArea.style.width = '2em';
    textArea.style.height = '2em';

    // We don't need padding, reducing the size if it does flash render.
    textArea.style.padding = 0;

    // Clean up any borders.
    textArea.style.border = 'none';
    textArea.style.outline = 'none';
    textArea.style.boxShadow = 'none';

    // Avoid flash of white box if rendered for any reason.
    textArea.style.background = 'transparent';

    textArea.value = text;

    document.body.appendChild(textArea);

    textArea.select();

    try {
        var successful = document.execCommand('copy');
        var msg = successful ? 'successful' : 'unsuccessful';
        console.log('Copying text command was ' + msg);
    } catch (err) {
        console.log('Oops, unable to copy');
    }

    document.body.removeChild(textArea);
}
```

**Comment by 6pac** [comment]
my new master https://github.com/6pac has a fully developed plugin for this based on @celebio's, with additional bug fixes.

see http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html

**Comment by alexcroox** [comment]
Ah very nice, is there a way to disable pasting back into the grid, e.g read only but with copy functionality still active?

**Comment by 6pac** [comment]
not at present, but that flag would be very easy to insert

**Comment by 6pac** [comment]
added plugin option 'readOnlyMode' in the latest push

**Comment by aniketng765** [comment]
how to disable paste for single column, selectable : false worked when i tried to paste for single column.
but when i copy data from two columns and try to paste on column besides the one having selectable : false, it allows to paste.

**Comment by 6pac** [comment]
should probably have a 'AllowPaste' option for columns - I don't think  [cannot select] always means [cannot paste]. Note comment above about the new master repo. Nothing is going to happen here.

**Comment by aniketng765** [comment]
AllowPaste is not working in case of columns,

`{
                    id: "PrpFixtureCode",
                    name: "Proposed Fixture Code",
                    field: "PrpFixtureCode",
                    toolTip: "Proposed Fixture Code",
                    width: 130,
                    sortable: true,
                    dataType: 'varchar',
                    required: false,
                    resizable: true,
                    focusable:false,
                    selectable : false,allowPaste : false
                    //headerCssClass:"columnColor",
                    //editor: Slick.Editors.Text,
                    //editable: true
                },`

code is like above but it still allow me to paste in Proposed Fixture Code columns if i try to paste multiple columns.

> should probably have a 'AllowPaste' option for columns - I don't think [cannot select] always means [cannot paste]. Note comment above about the new master repo. Nothing is going to happen here.

**Comment by 6pac** [comment]
The above about AllowPaste was only a suggestion for a possible fix. It is now implemented as colDef.denyPaste: see #1196
