### ISSUE TITLE
Checkbox state being lost after scrolling the row out and back in

### ISSUE THREAD

**Issue by TheSisb** [mleibman/SlickGrid#595]
I created a checkbox formatter:

```
function CheckBoxFormatter(row, cell, value, columnDef, dataContext) {  
    return "<input class='gridCheckBox' type=\"checkbox\" name=\""+value[0]+"\" value=\""+value[1]+"\" "+value[2]+">";
}
```

Once my page loads, I click some checkboxes and they gain the tick.  Then I scroll down 50 rows and back up, and all my ticks are gone.

I realize the formatter is not the editor, so I've created an editor.  But now the editor returns either an image (like in the demo) or some checkbox html that prevents the editor from being called on click.  I basically always want there to be a checkbox, so a formatter, but I also want to save the data.

Is there some way to trigger the editor on click from the formatter?
Which call is actually the one that saves the state of a cell?

**Comment by vinothkkl123** [comment]
In Slickgrid, I have check boxes in Header Row in 3 Columns, On-click  of  column 1 checkbox,  I have checked all the check boxes which is under the column.
I need to get the total check boxes in 3 columns and how many are checked?
E.g  Header Row Column -1 - 100 Checkboxes
       Header Row Column 2 - 25 Checkboxes
      Header Row Column 3 - 75 Checkboxes

So Overall 200 Checkboxes on the Page. How we can get the overall checkboxes count  on the page and get the checked checkboxes count on each column and all the columns?

Any Idea?

**Comment by 6pac** [comment]
@vinothkkl123 

This repo is dead. Please use: https://github.com/6pac/SlickGrid

Usage questions like this should be directed to StackOverflow, not the Github repo
