### ISSUE TITLE
Columns not displaying when loaded inside jQuery Accordion

### ISSUE THREAD

**Issue by jammy-git** [mleibman/SlickGrid#596]
I have several slickgrids inside jQuery UI accordions on a page. When the user clicks through to the next accordion, the grid won't load any columns beyond a certain column.

This is best demonstrated with the following JSFiddle: http://jsfiddle.net/DQ3U8/ - click on the header of the second accordion

If I load the accordions and grids inside window.setTimeout functions, and load the grids before the accordions are initialised then there isn't a problem. However to me this isn't acceptable as I would like to only load the grid once the accordion is opened, plus initialising using timeouts seems a really hacky way to do things!

**Comment by Domt301** [comment]
Im having this issue at the moment. Whenever my page reloads and the accordion is collapsed upon expanding the accordion the columns in the grid do not display properly. 
I tried using grid.resizeCanvas(); with no success/ 
http://stackoverflow.com/questions/29991072/slickgrid-inside-jquery-accordion-columns-not-displaying-properly

**Comment by 6pac** [comment]
I believe my 'alternative master' at https://github.com/6pac/SlickGrid has fixed this issue. The grid does not initialise properly if the parent element is hidden.
Alternatively, you can apply the changes from just this one commit to your fork:
https://github.com/6pac/SlickGrid/commit/687d38d755933830bcd889a3658b9dab8132060d

**Comment by Domt301** [comment]
![accordioned grid](https://cloud.githubusercontent.com/assets/11573996/7515804/2361ee00-f498-11e4-8bec-d1960839e0cd.PNG)
![after edit](https://cloud.githubusercontent.com/assets/11573996/7515808/2f584b96-f498-11e4-89c1-1017f42bb743.PNG)

**Comment by Domt301** [comment]
First thank you for your response!
Thats the before and after, the columns arent smashed anymore. The data is still not displaying properly and the columns are now huge. I feel like we're getting warmer. 

http://stackoverflow.com/questions/29991072/slickgrid-inside-jquery-accordion-columns-not-displaying-properly

Thats my question on stackoverflow. It has a 50 point bounty.

**Comment by 6pac** [comment]
A patch for this issue has been added to the 'alternative master' repo.
Repo: https://github.com/6pac/SlickGrid
Latest release: https://github.com/6pac/SlickGrid/releases
Blog post: http://low-bandwidth.blogspot.com.au/2015/06/slickgrid-with-jqueryui-and-bootstrap.html

The latest release has added examples for Bootstrap and the jQueryUI Accordion that may help provide a standardised page for testing, and demonstrate a known good configuration.

I note that in the demo page, once the CSS patches are applied, the order of loading (grid > accordion or accordion > grid) doesn't matter.
