### ISSUE TITLE
About Nested Header

### ISSUE THREAD

**Issue by QiangZhu** [mleibman/SlickGrid#63]
Hi,man
    Could you improve your slickgrid to support the nested header ,like 
http://www.sigmawidgets.com/products/sigma_grid2/demos/example_header_nested.html

```
                                                          Thank you for your hard work
```

**Comment by ataft** [comment]
You can do this in the active SlickGrid repo: https://github.com/6pac/SlickGrid

Here's an example: http://6pac.github.io/SlickGrid/examples/example-column-group.html
