### ISSUE TITLE
Horizontal scroll bar not coming

### ISSUE THREAD

**Issue by ritesh399** [mleibman/SlickGrid#642]
Hi, 
I am creating two grids at a time but one of them I am hiding by hiding the outer containing div.
The other grid is shown based upon selection of some option's in a drop down.(It's toggling between two grid's)
The issue is there is no horizontal scroll bar coming up for second grid after making it visible.

The pseudo grid is as below

<div id="grid1" class="class1">
    <div id="grid1Grid" class="class11"></div>
</div>

<div id="grid2" class="class2">
    <div id="grid2Grid" class="class22"></div>
</div>

gridI1= new Slick.Grid("#grid1Grid", dataView1, columns1, options);
gridI2= new Slick.Grid("#grid2Grid", dataView2, columns2, options);

$("#grid1").show();
$("#grid2").hide();

$("#grid2").show();
$("#grid1").hide();

Thanks.

**Comment by SherryXueyingLi** [comment]
I met this problem too and the solution is call  resizeCanvas(); after set data:

this.sgDataView.beginUpdate();
this.sgDataView.setItems(mappedArray, idField);
this.sgDataView.endUpdate();
this.sgGrid.resizeCanvas();
