### ISSUE TITLE
Slickgrid does not render columns correctly when used in a jquery ui tab

### ISSUE THREAD

**Issue by ghost** [mleibman/SlickGrid#711]
See this example for a reproduction of the issue. http://jsfiddle.net/cc7dE/

**Comment by SherryXueyingLi** [comment]
Thank you Jon your case is really helping.

**Comment by 6pac** [comment]
Might be worth checking out my 'alternate master' repo: https://github.com/6pac/SlickGrid. Updated jquery versions and many small fixes for issues like this. There is a jqueryui tab example page.

Also this blog post may help: http://low-bandwidth.blogspot.com.au/2015/06/slickgrid-with-jqueryui-and-bootstrap.html
