### ISSUE TITLE
jquery.event.drag conflicts with events in jquery.ui.draggable

### ISSUE THREAD

**Issue by dioptre** [mleibman/SlickGrid#723]
Hi I'm trying to use three 3rd party apps (one slickgrid).

The other two use jquery.draggable, and the threedubmedia event.drag lib conflicts with the other actions on the page (the dropping on the other components doesn't work). 

At first glance, re-implementing slickgrid to use the standard draggable lib looks like it might be the best way to fix.

What do you think?

Thanks
Andrew

**Comment by sneha8595** [comment]
+1 to the issue. i have tried the possible ways, but jquery.event.drag conflicts with events in jquery.ui.draggable. Can someone please provide a solution for this?
