### ISSUE TITLE
Conflict with bootstrap 3

### ISSUE THREAD

**Issue by Magicloud** [mleibman/SlickGrid#742]
With bootstrap.css, something on cell/header size calculating is wrong. So the cells of the same column of different rows are not aligned with the header.

Everything is back to normal after remove bootstrap. But our layout is totally based on bootstrap. So please help.

![screenshot from 2013-09-10 17 14 29](https://f.cloud.github.com/assets/1886157/1113317/6c9e7d70-19f9-11e3-9388-0cfed4c70741.png)

**Comment by dizzy0ny** [comment]
is this fix in the latest version of slickgrid?  or would i need to apply one of the recommended fixes above?

**Comment by 6pac** [comment]
I'll look at this and try to apply a patch soon. That said, I'm using bootstrap and haven't noticed enough of a problem for it to even register with me. However it's worth noting:
1) the behaviour of jQuery changed around 1.8 so the solution will depend on the version you're using. The master is at 1.7 and the alternate at 1.11.
2) this is definitely related to the css 'border-box' setting, which bootstrap uses
3) the two approaches are to 
  (a) turn border-box off for the slickgrid elements (he simplest approach), or 
  (b) modify the slickgrid code/css to use border-box, but this would have to be tested under both jQuery versions

**Comment by 6pac** [comment]
... to answer the question, currently this has not been patched on either master

**Comment by 6pac** [comment]
A patch for this issue has been added to the 'alternative master' repo. It should fix all cases.
Repo: https://github.com/6pac/SlickGrid
Latest release: https://github.com/6pac/SlickGrid/releases
Blog post: http://low-bandwidth.blogspot.com.au/2015/06/slickgrid-with-jqueryui-and-bootstrap.html

The latest release has added examples for Bootstrap and the jQueryUI Accordion that may help provide a standardised page for testing, and demonstrate a known good configuration.

**Comment by tanveer-ali** [comment]
I have to still enable the following slick.grid.css after getting the patch from @6pac  in order to work in firefox the first grid loads .. it was misaligned 

/*box-sizing: content-box !important;*/
to
  box-sizing: content-box !important; 

But enabling it fixed the issue

**Comment by mzabuawala** [comment]
I had same issue on Firefox, It was fixed by adding below code in my CSS.

```
  .slickgrid,
    .slickgrid *,
    .slick-header-column {

            box-sizing: content-box;
            -moz-box-sizing: content-box;
            -webkit-box-sizing: content-box;
            -ms-box-sizing: content-box;

    }
```

**Comment by 6pac** [comment]
the patches to my repo should handle either 'border-box' or 'content-box', through the mechanism of jQuery 1.8+ which should handle them correctly. 
It does appear that Firefox has an issue, however it appears to be something different again.

as such I'm leaving things as-is, and the above patches should be considered the official Firefox solution.
