### ISSUE TITLE
asyncPostRender may cause memory leaks

### ISSUE THREAD

**Issue by jonozzz** [mleibman/SlickGrid#82]
I used asyncPostRender() to bind some jQuery handlers to some of the cells. When these cells are deleted by either removeAllRows() or removeRowFromCache() all jQuery handlers are being left floating around because the DOM has been manipulated directly.

My idea was to allow the user to perform the cleanup through a callback if the asyncPostRender was used.

Thoughts?

**Comment by 6pac** [comment]
A patch for this issue has been added to the 'alternative master' repo. An example page demonstrating cleanup has been added to the repo. Any testing, particularly regarding memory leaks, is greatly appreciated.
Repo: https://github.com/6pac/SlickGrid
Blog post: http://low-bandwidth.blogspot.com.au/2015/06/slickgrid-async-post-render-cleanup.html

I haven't tagged this commit as the next release yet, just waiting for this commit to settle.
